name: Build
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the website
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: '_site/*'
  commit:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.repository == 'p3palazzo/tau0005'
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        submodules: 'recursive'
    - uses: actions/download-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git add .
        git commit -m "${{ env.commit_message }}" -a || git status
        git pull --ff-only
        git push
